### ISSUE TITLE
Open an issue on failure of scheduled installation check

### ISSUE THREAD

**Issue by victorlin** [nextstrain/conda-base#84]
As an alternative to the [brittle](https://github.com/nextstrain/conda-base/blob/3f130e6f297f1beb67cae2efdcbe3ab9a6c528e8/.github/workflows/installation.yaml#L7-L12) email notification setup, the workflow can be configured to open an issue in this repo with visibility to the team.

It would look something like this:

```yaml
- if: failure()
  name: Create issue
  run: | 
     gh issue create --title "Installation failure" --body <link to failed workflow run>
  env:
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN_NEXTSTRAIN_BOT }}
```

Credit: https://github.com/orgs/community/discussions/43415#discussioncomment-9941115
